{% set name = "pytexit" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/erwanp/pytexit/archive/{{ version }}.tar.gz
  sha256: 3fa9f5010ee212bef1b0cb0e2b8383473b7f76144a343e97140fb751e463e7dd

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - six
test:
  source_files:
    - pytexit/test
  requires:
    - pip
    - pytest
    - pytest-cov
    - python {{ python_min }}
  commands:
    - pip check
    - cd pytexit/test
    - pytest .

about:
  home: https://github.com/erwanp/pytexit
  license: "CECILL-2.1"
  license_family: OTHER
  license_file: LICENSE
  summary: "Convert a Python expression to a LaTeX formula"


extra:
  recipe-maintainers:
    - Krande
